version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: loccubu/mern-backend:1.0
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mernapp
    depends_on:
      - mongodb

  frontend:
    image: loccubu/mern-frontend:2.0
    container_name: mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: